### PR TITLE
Add first half of scene 2 climb

### PR DESCRIPTION
**Pull request by cutburn**
Made alternate click funcs visible to scene 2 code and added first part of tree climbing.

### CODE REVIEW

**Comment by cutburn** [comment]
Sorry for all the shifting-crud-around diffs, hoping this'll be the last one for a bit. Did a run-through and it doesn't look like I broke anything but if so lemme know!

**Comment by inivekin** [comment]
Cool. I'll have a bunch of time tomorrow so I hope to dedicate that day to generally fixing my code and neatening everything up finally. Hopefully I'll make it easier for you to deal my code.

**Review by inivekin — COMMENTED** [review]
No problems. I don't think the failed clicks are necessary in scene 2. I ignored them during the running scene by leaving them blank. But now that I think about it, perhaps adding a listener so that if the wrong click is made a 'you pressed the wrong button' sound is made. Though this may be to jarring for a scene that is meant to be calming.

**Comment by cutburn** [comment]
Cool, thanks for the feedback - wasn't really sure what to do with them but knew I needed them per the implementation. Maybe I'll go back at some point and fix `alternateClicks` and the places that call it when it's worth the cleanup.

**Pull request merged**
